/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.tdd;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }

  @Test
  void greetingShouldBeHelloWorld() {
    App classUnderTest = new App();
    assertEquals("Hello, World", classUnderTest.getGreeting(), "greeting should be 'Hello, World!'");
  }
}
